# Generated by Django 2.1.4 on 2018-12-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_pid', models.IntegerField()),
                ('p_product', models.CharField(max_length=30)),
                ('p_price', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
