# Generated by Django 2.1.4 on 2018-12-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='catogery',
        ),
        migrations.AlterModelTable(
            name='catogery',
            table='catogery',
        ),
    ]
